-- Safe migration: Only add/drop/modify columns if needed
-- You may need to run these as separate statements in MySQL

-- Drop columns if they exist
ALTER TABLE staff DROP COLUMN IF EXISTS userId;
ALTER TABLE staff DROP COLUMN IF EXISTS password;

-- Add columns if they do not exist
ALTER TABLE staff ADD COLUMN IF NOT EXISTS passwordHash VARCHAR(255);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS mustChangePassword INT NOT NULL DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS lastSignedIn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS role ENUM('admin', 'counselor', 'viewer') NOT NULL DEFAULT 'counselor';
ALTER TABLE staff ADD COLUMN IF NOT EXISTS isVipRated INT NOT NULL DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS isAdmin INT NOT NULL DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS createdBy INT NOT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS updatedBy INT NOT NULL;

-- Modify primary key if needed
ALTER TABLE staff MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY;

-- Add columns for organization if not present
ALTER TABLE staff ADD COLUMN IF NOT EXISTS groupId INT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS staffDepartmentId INT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS teamId INT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS email VARCHAR(320);
